In [22]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/competitions/pokemon-tcg-ai-battle/Card_ID List_JP.pdf
/kaggle/input/competitions/pokemon-tcg-ai-battle/Card_ID List_EN.pdf
/kaggle/input/competitions/pokemon-tcg-ai-battle/EN_Card_Data.csv
/kaggle/input/competitions/pokemon-tcg-ai-battle/JP_Card_Data.csv
/kaggle/input/competitions/pokemon-tcg-ai-battle/sample_submission/sample_submission/deck.csv
/kaggle/input/competitions/pokemon-tcg-ai-battle/sample_submission/sample_submission/main.py
/kaggle/input/competitions/pokemon-tcg-ai-battle/sample_submission/sample_submission/cg/sim.py
/kaggle/input/competitions/pokemon-tcg-ai-battle/sample_submission/sample_submission/cg/libcg.dylib
/kaggle/input/competitions/pokemon-tcg-ai-battle/sample_submission/sample_submission/cg/game.py
/kaggle/input/competitions/pokemon-tcg-ai-battle/sample_submission/sample_submission/cg/libcg.so
/kaggle/input/competitions/pokemon-tcg-ai-battle/sample_submission/sample_submission/cg/utils.py
/kaggle/input/competitions/pokemon-tcg-ai-battle/sample_submission/sample_submission/cg/api.py
/kaggle/input/competitions/pokemon-tcg-ai-battle/sample_submission/sample_submission/cg/__init__.py
/kaggle/input/competitions/pokemon-tcg-ai-battle/sample_submission/sample_submission/cg/libcg-arm64.so
/kaggle/input/competitions/pokemon-tcg-ai-battle/sample_submission/sample_submission/cg/cg.dll

In [23]:
import kaggle_environments
print(kaggle_environments.__version__)

1.29.3

In [24]:
from kaggle_environments import make
env = make("cabt")
print("Environment loaded successfully!")

Environment loaded successfully!

In [25]:
import random

def random_agent(obs_dict):
    return random.sample(
        list(range(len(obs_dict["select"]["option"]))), 
        obs_dict["select"]["maxCount"]
    )

# Run a quick match using the simulator's own deck-building (or we'll need real deck IDs)
env = make("cabt", configuration={"episodeSteps": 50})
env.reset()
print(env.state)

[{'action': [], 'reward': 0, 'info': {}, 'observation': {'remainingOverageTime': 600, 'step': 0, 'select': None, 'logs': [], 'current': None, 'search_begin_input': None}, 'status': 'ACTIVE'}, {'action': [], 'reward': 0, 'info': {}, 'observation': {'remainingOverageTime': 600, 'select': None, 'logs': [], 'current': None, 'search_begin_input': None}, 'status': 'ACTIVE'}]

In [26]:
from kaggle_environments.envs.cabt.api import all_card_data

cards = all_card_data()
print(type(cards))
print(len(cards))
print(cards[:3])  # show first 3 cards to see the structure

ModuleNotFoundError: No module named 'kaggle_environments.envs.cabt.api'

In [ ]:
import kaggle_environments
import os

cabt_path = os.path.join(os.path.dirname(kaggle_environments.__file__), "envs", "cabt")
print(os.listdir(cabt_path))

In [ ]:
import subprocess
result = subprocess.run(
    ["grep", "-r", "def all_card_data", cabt_path],
    capture_output=True, text=True
)
print(result.stdout)
print(result.stderr)

In [ ]:
import subprocess

result = subprocess.run(
    ["grep", "-r", "def all_card_data", cabt_path],
    capture_output=True, text=True
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr)

In [ ]:
import os

def search_for_function(root_dir, function_name):
    matches = []
    for dirpath, dirnames, filenames in os.walk(root_dir):
        for filename in filenames:
            if filename.endswith(".py"):
                full_path = os.path.join(dirpath, filename)
                try:
                    with open(full_path, "r", encoding="utf-8") as f:
                        content = f.read()
                        if function_name in content:
                            matches.append(full_path)
                except Exception as e:
                    pass
    return matches

matches = search_for_function(cabt_path, "all_card_data")
print(matches)

In [ ]:
import os
import kaggle_environments

cabt_path = os.path.join(os.path.dirname(kaggle_environments.__file__), "envs", "cabt")
print(cabt_path)
print(os.listdir(cabt_path))

In [ ]:
def search_for_function(root_dir, function_name):
    matches = []
    for dirpath, dirnames, filenames in os.walk(root_dir):
        for filename in filenames:
            if filename.endswith(".py"):
                full_path = os.path.join(dirpath, filename)
                try:
                    with open(full_path, "r", encoding="utf-8") as f:
                        content = f.read()
                        if function_name in content:
                            matches.append(full_path)
                except Exception:
                    pass
    return matches

matches = search_for_function(cabt_path, "all_card_data")
print(matches)

In [ ]:
cg_path = os.path.join(cabt_path, "cg")
print(os.listdir(cg_path))

In [ ]:
def search_for_text(root_dir, search_text):
    matches = []
    for dirpath, dirnames, filenames in os.walk(root_dir):
        for filename in filenames:
            if filename.endswith(".py"):
                full_path = os.path.join(dirpath, filename)
                try:
                    with open(full_path, "r", encoding="utf-8") as f:
                        content = f.read()
                        if search_text in content:
                            matches.append(full_path)
                except Exception:
                    pass
    return matches

print(search_for_text(cabt_path, "card_data"))

In [ ]:
sim_path = os.path.join(cg_path, "sim.py")
with open(sim_path, "r", encoding="utf-8") as f:
    print(f.read())

In [ ]:
game_path = os.path.join(cg_path, "game.py")
with open(game_path, "r", encoding="utf-8") as f:
    print(f.read())

In [ ]:
print(search_for_text(cabt_path, "all_card_data"))
print(search_for_text(cabt_path, "def "))  # just to see what functions exist generally, broad sweep

In [ ]:
ke_root = os.path.dirname(kaggle_environments.__file__)
print(search_for_text(ke_root, "all_card_data"))

In [ ]:
cabt_py_path = os.path.join(cabt_path, "cabt.py")
with open(cabt_py_path, "r", encoding="utf-8") as f:
    print(f.read())

In [ ]:
import random
from kaggle_environments import make

deck = [
    721, 721, 722, 722, 722, 722, 723, 723, 723, 723,
    1092, 1121, 1121, 1145, 1145, 1163, 1163,
    1219, 1219, 1219, 1219, 1227, 1227, 1227, 1227,
    1262, 1262,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3
]

def random_agent(obs_dict):
    if obs_dict["select"] is None:
        return deck
    return random.sample(
        list(range(len(obs_dict["select"]["option"]))),
        obs_dict["select"]["maxCount"]
    )

env = make("cabt", configuration={"episodeSteps": 200})
result = env.run([random_agent, random_agent])

print("Game finished!")
print("Final status:", [result[-1][0]["status"], result[-1][1]["status"]])
print("Final reward:", [result[-1][0]["reward"], result[-1][1]["reward"]])

In [ ]:
print(len(deck))

In [ ]:
env = make("cabt", configuration={"episodeSteps": 200})
result = env.run([random_agent, random_agent])

print("Game finished!")
print("Final status:", [result[-1][0]["status"], result[-1][1]["status"]])
print("Final reward:", [result[-1][0]["reward"], result[-1][1]["reward"]])

In [ ]:
deck = [
    721, 721, 722, 722, 722, 722, 723, 723, 723, 723,
    1092, 1121, 1121, 1145, 1145, 1163, 1163,
    1219, 1219, 1219, 1219, 1227, 1227, 1227, 1227,
    1262, 1262,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3
]

print(len(deck))  # confirm it's now 60

In [ ]:
for i, step in enumerate(result):
    obs0 = step[0]["observation"]
    if obs0["select"] is not None:
        print(f"Step {i} has a real decision point!")
        print(obs0["select"])
        break

In [ ]:
SELECT_TYPE_YES_NO = 9
SELECT_TYPE_CARD = 1
SELECT_TYPE_ATTACK = 6
SELECT_TYPE_EVOLVE = 7
SELECT_TYPE_MAIN = 0

CONTEXT_IS_FIRST = 41
CONTEXT_ATTACK = 35
CONTEXT_SETUP_ACTIVE = 1
CONTEXT_SETUP_BENCH = 2

OPTION_YES = 1
OPTION_NO = 2


def decide_action(obs_dict):
    if obs_dict["select"] is None:
        return deck  # deck submission phase

    select = obs_dict["select"]
    select_type = select["type"]
    context = select["context"]
    options = select["option"]

    # Rule 1: Coin toss — always choose to go first
    if select_type == SELECT_TYPE_YES_NO and context == CONTEXT_IS_FIRST:
        for i, opt in enumerate(options):
            if opt["type"] == OPTION_YES:
                return [i]

    # Fallback for anything we haven't built logic for yet
    return list(range(select["minCount"]))


def my_agent(obs_dict):
    return decide_action(obs_dict)

In [ ]:
env = make("cabt", configuration={"episodeSteps": 200})
result = env.run([my_agent, random_agent])

print("Game finished!")
print("Final status:", [result[-1][0]["status"], result[-1][1]["status"]])
print("Final reward:", [result[-1][0]["reward"], result[-1][1]["reward"]])

In [ ]:
import random
from kaggle_environments import make

deck = [
    721, 721, 722, 722, 722, 722, 723, 723, 723, 723,
    1092, 1121, 1121, 1145, 1145, 1163, 1163,
    1219, 1219, 1219, 1219, 1227, 1227, 1227, 1227,
    1262, 1262,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3
]
print("Deck length:", len(deck))

def random_agent(obs_dict):
    if obs_dict["select"] is None:
        return deck
    return random.sample(
        list(range(len(obs_dict["select"]["option"]))),
        obs_dict["select"]["maxCount"]
    )

SELECT_TYPE_YES_NO = 9
CONTEXT_IS_FIRST = 41
OPTION_YES = 1

def decide_action(obs_dict):
    if obs_dict["select"] is None:
        return deck

    select = obs_dict["select"]
    select_type = select["type"]
    context = select["context"]
    options = select["option"]

    if select_type == SELECT_TYPE_YES_NO and context == CONTEXT_IS_FIRST:
        for i, opt in enumerate(options):
            if opt["type"] == OPTION_YES:
                return [i]

    return list(range(select["minCount"]))

def my_agent(obs_dict):
    return decide_action(obs_dict)

In [ ]:
env = make("cabt", configuration={"episodeSteps": 200})
result = env.run([my_agent, random_agent])

print("Game finished!")
print("Final status:", [result[-1][0]["status"], result[-1][1]["status"]])
print("Final reward:", [result[-1][0]["reward"], result[-1][1]["reward"]])

In [ ]:
wins = 0
losses = 0
draws = 0

for game_num in range(20):
    env = make("cabt", configuration={"episodeSteps": 200})
    result = env.run([my_agent, random_agent])
    reward = result[-1][0]["reward"]
    
    if reward == 1:
        wins += 1
    elif reward == -1:
        losses += 1
    else:
        draws += 1

print(f"Wins: {wins}, Losses: {losses}, Draws: {draws}")
print(f"Win rate: {wins/20*100:.1f}%")

In [ ]:
try:
    from kaggle_environments.envs.cabt.cg.api import all_card_data, all_attack
    print("Found api module with functions!")
except ImportError as e:
    print("Import failed:", e)

In [ ]:
import subprocess
result = subprocess.run(["pip", "install", "--upgrade", "kaggle-environments"], capture_output=True, text=True)
print(result.stdout[-2000:])
print(result.stderr[-2000:])

In [ ]:
env = make("cabt", configuration={"episodeSteps": 200})
result = env.run([random_agent, random_agent])

for i, step in enumerate(result):
    obs0 = step[0]["observation"]
    if obs0["current"] is not None:
        active = obs0["current"]["players"][0]["active"]
        if active and len(active) > 0:
            print(f"Step {i}: Active Pokemon data:")
            print(active[0])
            break

In [ ]:
import os
print(os.listdir("/kaggle/input"))

In [ ]:
import os

comp_path = "/kaggle/input/competitions"
print(os.listdir(comp_path))

In [ ]:
import os

print(os.listdir("/kaggle/input"))

for item in os.listdir("/kaggle/input"):
    full = os.path.join("/kaggle/input", item)
    print(repr(full), "-- isdir:", os.path.isdir(full))

In [1]:
import os
print(os.listdir("/kaggle/input"))

['competitions']

In [2]:
import os

base = "/kaggle/input/competitions"
print(os.listdir(base))

['pokemon-tcg-ai-battle']

In [3]:
import os

card_data_path = "/kaggle/input/competitions/pokemon-tcg-ai-battle"
print(os.listdir(card_data_path))

['sample_submission', 'Card_ID List_JP.pdf', 'Card_ID List_EN.pdf', 'EN_Card_Data.csv', 'JP_Card_Data.csv']

In [4]:
import pandas as pd

card_data = pd.read_csv("/kaggle/input/competitions/pokemon-tcg-ai-battle/EN_Card_Data.csv")
print(card_data.shape)
print(card_data.columns.tolist())
card_data.head(10)

(2022, 17)
['Card ID', 'Card Name', 'Expansion', 'Collection No.', 'Stage (Pokémon)/Type (Energy and Trainer)', 'Rule', 'Category', 'Previous stage', 'HP', 'Type', 'Weakness', 'Resistance (Type)', 'Retreat', 'Move Name', 'Cost', 'Damage', 'Effect Explanation']

,Card ID,Card Name,Expansion,Collection No.,Stage (Pokémon)/Type (Energy and Trainer),Rule,Category,Previous stage,HP,Type,Weakness,Resistance (Type),Retreat,Move Name,Cost,Damage,Effect Explanation
0,1,Basic {G} Energy,SVE,1,Basic Energy,NaN,NaN,NaN,NaN,{G},NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Basic {R} Energy,SVE,2,Basic Energy,NaN,NaN,NaN,NaN,{R},NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Basic {W} Energy,SVE,3,Basic Energy,NaN,NaN,NaN,NaN,{W},NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Basic {L} Energy,SVE,4,Basic Energy,NaN,NaN,NaN,NaN,{L},NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Basic {P} Energy,SVE,5,Basic Energy,NaN,NaN,NaN,NaN,{P},NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,Basic {F} Energy,SVE,6,Basic Energy,NaN,NaN,NaN,NaN,{F},NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,Basic {D} Energy,SVE,7,Basic Energy,NaN,NaN,NaN,NaN,{D},NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,Basic {M} Energy,SVE,8,Basic Energy,NaN,NaN,NaN,NaN,{M},NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,Boomerang Energy,TWM,166,Special Energy,NaN,NaN,NaN,NaN,{C},NaN,NaN,NaN,NaN,NaN,NaN,"As long as this card is attached to a Pokémon,..."
9,10,Neo Upper Energy,TEF,162,Special Energy,ACE SPEC,NaN,NaN,NaN,{A}{A},NaN,NaN,NaN,NaN,NaN,NaN,"As long as this card is attached to a Pokémon,..."

In [5]:
pokemon_cards = card_data[card_data["Category"] == "Pokémon"]
print(pokemon_cards.shape)
pokemon_cards.head(5)

(0, 17)

Empty DataFrame
Columns: [Card ID, Card Name, Expansion, Collection No., Stage (Pokémon)/Type (Energy and Trainer), Rule, Category, Previous stage, HP, Type, Weakness, Resistance (Type), Retreat, Move Name, Cost, Damage, Effect Explanation]
Index: []

In [6]:
print(card_data["Category"].unique())

[nan "Trainer's Pokémon（Team Rocket）" 'Future' 'Tera(Fire)' 'Ancient'
 'Tera(Fighting)' 'Tera(Lightning)' 'Tera(Darkness)' 'Tera(Grass)'
 'Tera(Water)' 'Tera(Dragon)' 'Tera(Stellar)' "Trainer's Pokémon（N）"
 "Trainer's Pokémon（Iono）" "Trainer's Pokémon（Lillie）"
 "Trainer's Pokémon（Hop）" "Trainer's Pokémon（Ethan）"
 "Trainer's Pokémon（Cynthia）" "Trainer's Pokémon（Misty）"
 "Trainer's Pokémon（Arven）" "Trainer's Pokémon（Steven）"
 "Trainer's Pokémon（Marnie）" "Trainer's Pokémon（Erika）"
 "Trainer's Pokémon（Larry）" 'Fossil' 'Technical Machine']

In [7]:
print(card_data["Stage (Pokémon)/Type (Energy and Trainer)"].unique())

['Basic Energy' 'Special Energy' 'Stage 1 Pokémon' 'Basic Pokémon'
 'Stage 2 Pokémon' 'Item' 'Pokémon Tool' 'Supporter' 'Stadium']

In [8]:
pokemon_types = ["Basic Pokémon", "Stage 1 Pokémon", "Stage 2 Pokémon"]
pokemon_cards = card_data[card_data["Stage (Pokémon)/Type (Energy and Trainer)"].isin(pokemon_types)]

print(pokemon_cards.shape)
pokemon_cards.head(5)

(1805, 17)

,Card ID,Card Name,Expansion,Collection No.,Stage (Pokémon)/Type (Energy and Trainer),Rule,Category,Previous stage,HP,Type,Weakness,Resistance (Type),Retreat,Move Name,Cost,Damage,Effect Explanation
20,21,Scrafty,PROMO,188,Stage 1 Pokémon,NaN,NaN,Scraggy,120.0,{D},{G},NaN,1.0,Nab ’n’ Dash,●,NaN,Search your deck for a number of cards up to t...
21,21,Scrafty,PROMO,188,Stage 1 Pokémon,NaN,NaN,Scraggy,120.0,{D},{G},NaN,1.0,High Jump Kick,{D}●●,100,NaN
22,22,Hippopotas,DRI,105,Basic Pokémon,NaN,NaN,NaN,90.0,{F},{G},NaN,3.0,Push Down,{F},10,Switch out your opponent’s Active Pokémon to t...
23,23,Hippowdon,DRI,106,Stage 1 Pokémon,NaN,NaN,Hippopotas,160.0,{F},{G},NaN,4.0,Ram,{F}{F},60,NaN
24,23,Hippowdon,DRI,106,Stage 1 Pokémon,NaN,NaN,Hippopotas,160.0,{F},{G},NaN,4.0,Super Sandstorm,{F}{F}●,150,This attack also does 40 damage to each Benche...

In [9]:
def parse_energy_cost(cost_string):
    if pd.isna(cost_string):
        return []
    
    energy_map = {
        "G": "Grass",
        "R": "Fire",
        "W": "Water",
        "L": "Lightning",
        "P": "Psychic",
        "F": "Fighting",
        "D": "Darkness",
        "M": "Metal",
        "A": "Dragon",  # need to verify this one
    }
    
    costs = []
    i = 0
    while i < len(cost_string):
        char = cost_string[i]
        if char == "{":
            # find matching closing brace
            end = cost_string.index("}", i)
            symbol = cost_string[i+1:end]
            costs.append(energy_map.get(symbol, symbol))
            i = end + 1
        elif char == "●":
            costs.append("Colorless")
            i += 1
        else:
            i += 1
    return costs


# Test it on Hippowdon's Super Sandstorm attack
print(parse_energy_cost("{F}{F}●"))
print(parse_energy_cost("{D}●●"))
print(parse_energy_cost("●"))

['Fighting', 'Fighting', 'Colorless']
['Darkness', 'Colorless', 'Colorless']
['Colorless']

The Challenge: One Card Can Span Multiple Rows

In [12]:
def build_card_lookup(card_data):
    lookup = {}
    
    for _, row in card_data.iterrows():
        card_id = row["Card ID"]
        
        if card_id not in lookup:
            lookup[card_id] = {
                "name": row["Card Name"],
                "category": row["Stage (Pokémon)/Type (Energy and Trainer)"],
                "hp": row["HP"] if pd.notna(row["HP"]) else None,
                "type": row["Type"] if pd.notna(row["Type"]) else None,
                "weakness": row["Weakness"] if pd.notna(row["Weakness"]) else None,
                "retreat_cost": row["Retreat"] if pd.notna(row["Retreat"]) else None,
                "attacks": []
            }
        
        if pd.notna(row["Move Name"]):
            lookup[card_id]["attacks"].append({
                "name": row["Move Name"],
                "cost": parse_energy_cost(row["Cost"]),
                "damage": row["Damage"] if pd.notna(row["Damage"]) else 0,
                "effect": row["Effect Explanation"] if pd.notna(row["Effect Explanation"]) else None
            })
    
    return lookup

In [13]:
card_lookup = build_card_lookup(card_data)

# Test with Scrafty (card ID 21)
print(card_lookup[21])

{'name': 'Scrafty', 'category': 'Stage 1 Pokémon', 'hp': 120.0, 'type': '{D}', 'weakness': '{G}', 'retreat_cost': 1.0, 'attacks': [{'name': 'Nab ’n’ Dash', 'cost': ['Colorless'], 'damage': 0, 'effect': 'Search your deck for a number of cards up to the number of your Benched Pokémon and put them into your hand. Then, shuffle your deck.'}, {'name': 'High Jump Kick', 'cost': ['Darkness', 'Colorless', 'Colorless'], 'damage': '100', 'effect': None}]}

In [14]:
ENERGY_SYMBOL_MAP = {
    "G": "Grass",
    "R": "Fire",
    "W": "Water",
    "L": "Lightning",
    "P": "Psychic",
    "F": "Fighting",
    "D": "Darkness",
    "M": "Metal",
    "C": "Colorless",
    "N": "Dragon",
}

def clean_symbol(symbol_string):
    if pd.isna(symbol_string):
        return None
    # Strip the curly braces, look up the letter
    letter = symbol_string.strip("{}")
    return ENERGY_SYMBOL_MAP.get(letter, letter)

In [15]:
"type": clean_symbol(row["Type"]),
"weakness": clean_symbol(row["Weakness"]),

SyntaxError: illegal target for annotation (1567247880.py, line 1)

In [16]:
ENERGY_SYMBOL_MAP = {
    "G": "Grass",
    "R": "Fire",
    "W": "Water",
    "L": "Lightning",
    "P": "Psychic",
    "F": "Fighting",
    "D": "Darkness",
    "M": "Metal",
    "C": "Colorless",
    "N": "Dragon",
}

def clean_symbol(symbol_string):
    if pd.isna(symbol_string):
        return None
    letter = symbol_string.strip("{}")
    return ENERGY_SYMBOL_MAP.get(letter, letter)


def build_card_lookup(card_data):
    lookup = {}
    
    for _, row in card_data.iterrows():
        card_id = row["Card ID"]
        
        if card_id not in lookup:
            lookup[card_id] = {
                "name": row["Card Name"],
                "category": row["Stage (Pokémon)/Type (Energy and Trainer)"],
                "hp": row["HP"] if pd.notna(row["HP"]) else None,
                "type": clean_symbol(row["Type"]),
                "weakness": clean_symbol(row["Weakness"]),
                "retreat_cost": row["Retreat"] if pd.notna(row["Retreat"]) else None,
                "attacks": []
            }
        
        if pd.notna(row["Move Name"]):
            lookup[card_id]["attacks"].append({
                "name": row["Move Name"],
                "cost": parse_energy_cost(row["Cost"]),
                "damage": row["Damage"] if pd.notna(row["Damage"]) else 0,
                "effect": row["Effect Explanation"] if pd.notna(row["Effect Explanation"]) else None
            })
    
    return lookup


card_lookup = build_card_lookup(card_data)
print(card_lookup[21])

{'name': 'Scrafty', 'category': 'Stage 1 Pokémon', 'hp': 120.0, 'type': 'Darkness', 'weakness': 'Grass', 'retreat_cost': 1.0, 'attacks': [{'name': 'Nab ’n’ Dash', 'cost': ['Colorless'], 'damage': 0, 'effect': 'Search your deck for a number of cards up to the number of your Benched Pokémon and put them into your hand. Then, shuffle your deck.'}, {'name': 'High Jump Kick', 'cost': ['Darkness', 'Colorless', 'Colorless'], 'damage': '100', 'effect': None}]}

In [17]:
charizard_rows = card_data[card_data["Card Name"].str.contains("Charizard", na=False)]
print(charizard_rows[["Card ID", "Card Name", "Type", "Weakness"]])

      Card ID            Card Name Type Weakness
1362      790  Mega Charizard X ex  {R}      {W}
1581      928  Mega Charizard Y ex  {R}      {W}

In [19]:
print(card_data.columns.tolist())

['Card ID', 'Card Name', 'Expansion', 'Collection No.', 'Stage (Pokémon)/Type (Energy and Trainer)', 'Rule', 'Category', 'Previous stage', 'HP', 'Type', 'Weakness', 'Resistance (Type)', 'Retreat', 'Move Name', 'Cost', 'Damage', 'Effect Explanation']

In [20]:
env = make("cabt", configuration={"episodeSteps": 200})
result = env.run([random_agent, random_agent])

for i, step in enumerate(result):
    obs0 = step[0]["observation"]
    if obs0["select"] is not None and obs0["select"]["context"] == 35:  # CONTEXT_ATTACK
        print(f"Step {i}:")
        print("Select:", obs0["select"])
        print("\nCurrent state - your active:", obs0["current"]["players"][obs0["current"]["yourIndex"]]["active"])
        break

NameError: name 'make' is not defined

In [21]:
import random
from kaggle_environments import make

deck = [
    721, 721, 722, 722, 722, 722, 723, 723, 723, 723,
    1092, 1121, 1121, 1145, 1145, 1163, 1163,
    1219, 1219, 1219, 1219, 1227, 1227, 1227, 1227,
    1262, 1262,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3
]

def random_agent(obs_dict):
    if obs_dict["select"] is None:
        return deck
    return random.sample(
        list(range(len(obs_dict["select"]["option"]))),
        obs_dict["select"]["maxCount"]
    )

env = make("cabt", configuration={"episodeSteps": 200})
result = env.run([random_agent, random_agent])

for i, step in enumerate(result):
    obs0 = step[0]["observation"]
    if obs0["select"] is not None and obs0["select"]["context"] == 35:  # CONTEXT_ATTACK
        print(f"Step {i}:")
        print("Select:", obs0["select"])
        print("\nCurrent state - your active:", obs0["current"]["players"][obs0["current"]["yourIndex"]]["active"])
        break
else:
    print("No attack decision point found in this game - try running again, or it may not have reached an attack phase")

[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO: Successfully loaded OpenSpiel environments: 24.
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_amazons
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_backgammon
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_checkers
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_chess
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_clobber
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_coin_game
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_coin_game_arena
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_connect_four
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_dark_hex
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_gin_rummy
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_go
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_goofspiel
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_hearts
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_hex
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_lines_of_action
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_matching_pennies_3p
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_oshi_zumo
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_othello
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_repeated_game
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_tic_tac_toe
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_y
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_universal_poker
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_repeated_poker
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_python_repeated_pokerkit
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO: OpenSpiel games skipped: 1.
[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    snake
No attack decision point found in this game - try running again, or it may not have reached an attack phase

In [22]:
for attempt in range(5):
    result = env.run([random_agent, random_agent])
    found = False
    for i, step in enumerate(result):
        obs0 = step[0]["observation"]
        if obs0["select"] is not None and obs0["select"]["context"] == 35:
            print(f"Found on attempt {attempt}, step {i}:")
            print("Select:", obs0["select"])
            print("\nCurrent state - your active:", obs0["current"]["players"][obs0["current"]["yourIndex"]]["active"])
            found = True
            break
    if found:
        break
else:
    print("Still not found after 5 attempts - something else may be going on")

Still not found after 5 attempts - something else may be going on

In [23]:
result = env.run([random_agent, random_agent])

print("Total steps:", len(result))
print("Final status:", [result[-1][0]["status"], result[-1][1]["status"]])
print("Final reward:", [result[-1][0]["reward"], result[-1][1]["reward"]])

# Print every unique select context we actually encountered
contexts_seen = set()
for step in result:
    obs0 = step[0]["observation"]
    if obs0["select"] is not None:
        contexts_seen.add(obs0["select"]["context"])

print("\nAll select contexts seen in this game:", contexts_seen)

Total steps: 16
Final status: ['DONE', 'DONE']
Final reward: [-1, 1]

All select contexts seen in this game: {0, 41, 1}

In [24]:
for i, step in enumerate(result):
    obs0 = step[0]["observation"]
    print(f"Step {i}: select context = {obs0['select']['context'] if obs0['select'] else None}, logs = {obs0['logs']}")

Step 0: select context = None, logs = []
Step 1: select context = 41, logs = []
Step 2: select context = 41, logs = []
Step 3: select context = 1, logs = [{'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 50}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 43}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 61}, {'type': 4, 'playerIndex': 0, 'cardId': 722, 'serial': 6}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 60}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 40}, {'type': 4, 'playerIndex': 0, 'cardId': 723, 'serial': 12}, {'type': 1, 'playerIndex': 1, 'hasBasicPokemon': True}, {'type': 1, 'playerIndex': 0, 'hasBasicPokemon': True}, {'type': 7, 'playerIndex': 1, 'fromArea': 2, 'toArea': 4}]
Step 4: select context = 1, logs = [{'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 50}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 43}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 61}, {'type': 4, 'playerIndex': 0, 'cardId': 722, 'serial': 6}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 60}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 40}, {'type': 4, 'playerIndex': 0, 'cardId': 723, 'serial': 12}, {'type': 1, 'playerIndex': 1, 'hasBasicPokemon': True}, {'type': 1, 'playerIndex': 0, 'hasBasicPokemon': True}, {'type': 7, 'playerIndex': 1, 'fromArea': 2, 'toArea': 4}]
Step 5: select context = 1, logs = [{'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 50}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 43}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 61}, {'type': 4, 'playerIndex': 0, 'cardId': 722, 'serial': 6}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 60}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 40}, {'type': 4, 'playerIndex': 0, 'cardId': 723, 'serial': 12}, {'type': 1, 'playerIndex': 1, 'hasBasicPokemon': True}, {'type': 1, 'playerIndex': 0, 'hasBasicPokemon': True}, {'type': 7, 'playerIndex': 1, 'fromArea': 2, 'toArea': 4}]
Step 6: select context = 1, logs = [{'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 50}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 43}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 61}, {'type': 4, 'playerIndex': 0, 'cardId': 722, 'serial': 6}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 60}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 40}, {'type': 4, 'playerIndex': 0, 'cardId': 723, 'serial': 12}, {'type': 1, 'playerIndex': 1, 'hasBasicPokemon': True}, {'type': 1, 'playerIndex': 0, 'hasBasicPokemon': True}, {'type': 7, 'playerIndex': 1, 'fromArea': 2, 'toArea': 4}]
Step 7: select context = 0, logs = [{'type': 6, 'playerIndex': 0, 'cardId': 722, 'serial': 6, 'fromArea': 2, 'toArea': 4}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 2, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 11, 'playerIndex': 1, 'cardId': 3, 'serial': 120, 'cardIdTarget': 722, 'serialTarget': 67}, {'type': 11, 'playerIndex': 1, 'cardId': 1163, 'serial': 78, 'cardIdTarget': 722, 'serialTarget': 67}, {'type': 3, 'playerIndex': 1}, {'type': 2, 'playerIndex': 0}, {'type': 4, 'playerIndex': 0, 'cardId': 1121, 'serial': 15}]
Step 8: select context = 0, logs = [{'type': 6, 'playerIndex': 0, 'cardId': 722, 'serial': 6, 'fromArea': 2, 'toArea': 4}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 2, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 11, 'playerIndex': 1, 'cardId': 3, 'serial': 120, 'cardIdTarget': 722, 'serialTarget': 67}, {'type': 11, 'playerIndex': 1, 'cardId': 1163, 'serial': 78, 'cardIdTarget': 722, 'serialTarget': 67}, {'type': 3, 'playerIndex': 1}, {'type': 2, 'playerIndex': 0}, {'type': 4, 'playerIndex': 0, 'cardId': 1121, 'serial': 15}]
Step 9: select context = 0, logs = [{'type': 6, 'playerIndex': 0, 'cardId': 722, 'serial': 6, 'fromArea': 2, 'toArea': 4}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 1, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 7, 'playerIndex': 0, 'fromArea': 1, 'toArea': 6}, {'type': 2, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 11, 'playerIndex': 1, 'cardId': 3, 'serial': 120, 'cardIdTarget': 722, 'serialTarget': 67}, {'type': 11, 'playerIndex': 1, 'cardId': 1163, 'serial': 78, 'cardIdTarget': 722, 'serialTarget': 67}, {'type': 3, 'playerIndex': 1}, {'type': 2, 'playerIndex': 0}, {'type': 4, 'playerIndex': 0, 'cardId': 1121, 'serial': 15}]
Step 10: select context = 0, logs = [{'type': 3, 'playerIndex': 0}, {'type': 2, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 11, 'playerIndex': 1, 'cardId': 3, 'serial': 100, 'cardIdTarget': 722, 'serialTarget': 67}, {'type': 15, 'playerIndex': 1, 'cardId': 722, 'serial': 67, 'attackId': 1045}, {'type': 16, 'playerIndex': 0, 'cardId': 722, 'serial': 6, 'value': -30, 'putDamageCounter': False}, {'type': 3, 'playerIndex': 1}, {'type': 2, 'playerIndex': 0}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 31}]
Step 11: select context = 0, logs = [{'type': 3, 'playerIndex': 0}, {'type': 2, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 11, 'playerIndex': 1, 'cardId': 3, 'serial': 100, 'cardIdTarget': 722, 'serialTarget': 67}, {'type': 15, 'playerIndex': 1, 'cardId': 722, 'serial': 67, 'attackId': 1045}, {'type': 16, 'playerIndex': 0, 'cardId': 722, 'serial': 6, 'value': -30, 'putDamageCounter': False}, {'type': 3, 'playerIndex': 1}, {'type': 2, 'playerIndex': 0}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 31}]
Step 12: select context = 0, logs = [{'type': 3, 'playerIndex': 0}, {'type': 2, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 11, 'playerIndex': 1, 'cardId': 3, 'serial': 100, 'cardIdTarget': 722, 'serialTarget': 67}, {'type': 15, 'playerIndex': 1, 'cardId': 722, 'serial': 67, 'attackId': 1045}, {'type': 16, 'playerIndex': 0, 'cardId': 722, 'serial': 6, 'value': -30, 'putDamageCounter': False}, {'type': 3, 'playerIndex': 1}, {'type': 2, 'playerIndex': 0}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 31}]
Step 13: select context = 0, logs = [{'type': 3, 'playerIndex': 0}, {'type': 2, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 11, 'playerIndex': 1, 'cardId': 3, 'serial': 100, 'cardIdTarget': 722, 'serialTarget': 67}, {'type': 15, 'playerIndex': 1, 'cardId': 722, 'serial': 67, 'attackId': 1045}, {'type': 16, 'playerIndex': 0, 'cardId': 722, 'serial': 6, 'value': -30, 'putDamageCounter': False}, {'type': 3, 'playerIndex': 1}, {'type': 2, 'playerIndex': 0}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 31}]
Step 14: select context = 0, logs = [{'type': 3, 'playerIndex': 0}, {'type': 2, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 11, 'playerIndex': 1, 'cardId': 3, 'serial': 100, 'cardIdTarget': 722, 'serialTarget': 67}, {'type': 15, 'playerIndex': 1, 'cardId': 722, 'serial': 67, 'attackId': 1045}, {'type': 16, 'playerIndex': 0, 'cardId': 722, 'serial': 6, 'value': -30, 'putDamageCounter': False}, {'type': 3, 'playerIndex': 1}, {'type': 2, 'playerIndex': 0}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 31}]
Step 15: select context = 0, logs = [{'type': 3, 'playerIndex': 0}, {'type': 2, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 11, 'playerIndex': 1, 'cardId': 3, 'serial': 100, 'cardIdTarget': 722, 'serialTarget': 67}, {'type': 15, 'playerIndex': 1, 'cardId': 722, 'serial': 67, 'attackId': 1045}, {'type': 16, 'playerIndex': 0, 'cardId': 722, 'serial': 6, 'value': -30, 'putDamageCounter': False}, {'type': 3, 'playerIndex': 1}, {'type': 2, 'playerIndex': 0}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 31}]

In [29]:
for i, step in enumerate(result):
    for player in [0, 1]:
        obs = step[player]["observation"]
        if obs["select"] is not None and obs["select"]["context"] == 35:
            print(f"Found! Step {i}, Player {player}")
            print(obs["select"])
            print()

In [30]:
print("Player 0 observation at step 10:")
print(result[10][0]["observation"])
print("\n\nPlayer 1 observation at step 10:")
print(result[10][1]["observation"])

Player 0 observation at step 10:
{'remainingOverageTime': 599.9999280000002, 'step': 10, 'select': {'type': 0, 'context': 0, 'minCount': 1, 'maxCount': 1, 'remainDamageCounter': 0, 'remainEnergyCost': 0, 'option': [{'type': 8, 'area': 2, 'index': 0, 'inPlayArea': 4, 'inPlayIndex': 0}, {'type': 8, 'area': 2, 'index': 1, 'inPlayArea': 4, 'inPlayIndex': 0}, {'type': 8, 'area': 2, 'index': 2, 'inPlayArea': 4, 'inPlayIndex': 0}, {'type': 8, 'area': 2, 'index': 3, 'inPlayArea': 4, 'inPlayIndex': 0}, {'type': 8, 'area': 2, 'index': 4, 'inPlayArea': 4, 'inPlayIndex': 0}, {'type': 9, 'area': 2, 'index': 5, 'inPlayArea': 4, 'inPlayIndex': 0}, {'type': 7, 'index': 6}, {'type': 8, 'area': 2, 'index': 7, 'inPlayArea': 4, 'inPlayIndex': 0}, {'type': 14}], 'deck': None, 'contextCard': None, 'effect': None}, 'logs': [{'type': 3, 'playerIndex': 0}, {'type': 2, 'playerIndex': 1}, {'type': 5, 'playerIndex': 1}, {'type': 11, 'playerIndex': 1, 'cardId': 3, 'serial': 100, 'cardIdTarget': 722, 'serialTarget': 67}, {'type': 15, 'playerIndex': 1, 'cardId': 722, 'serial': 67, 'attackId': 1045}, {'type': 16, 'playerIndex': 0, 'cardId': 722, 'serial': 6, 'value': -30, 'putDamageCounter': False}, {'type': 3, 'playerIndex': 1}, {'type': 2, 'playerIndex': 0}, {'type': 4, 'playerIndex': 0, 'cardId': 3, 'serial': 31}], 'current': {'turn': 4, 'turnActionCount': 1, 'yourIndex': 0, 'firstPlayer': 1, 'supporterPlayed': False, 'stadiumPlayed': False, 'energyAttached': False, 'retreated': False, 'result': -1, 'stadium': [], 'looking': None, 'players': [{'active': [{'id': 722, 'serial': 6, 'playerIndex': 0, 'hp': 60, 'maxHp': 90, 'appearThisTurn': False, 'energies': [], 'energyCards': [], 'tools': [], 'preEvolution': []}], 'bench': [], 'benchMax': 5, 'deckCount': 45, 'discard': [], 'prize': [None, None, None, None, None, None], 'handCount': 8, 'hand': [{'id': 3, 'serial': 50, 'playerIndex': 0}, {'id': 3, 'serial': 43, 'playerIndex': 0}, {'id': 3, 'serial': 61, 'playerIndex': 0}, {'id': 3, 'serial': 60, 'playerIndex': 0}, {'id': 3, 'serial': 40, 'playerIndex': 0}, {'id': 723, 'serial': 12, 'playerIndex': 0}, {'id': 1121, 'serial': 15, 'playerIndex': 0}, {'id': 3, 'serial': 31, 'playerIndex': 0}], 'poisoned': False, 'burned': False, 'asleep': False, 'paralyzed': False, 'confused': False}, {'active': [{'id': 722, 'serial': 67, 'playerIndex': 1, 'hp': 90, 'maxHp': 90, 'appearThisTurn': False, 'energies': [3, 3], 'energyCards': [{'id': 3, 'serial': 120, 'playerIndex': 1}, {'id': 3, 'serial': 100, 'playerIndex': 1}], 'tools': [{'id': 1163, 'serial': 78, 'playerIndex': 1}], 'preEvolution': []}], 'bench': [], 'benchMax': 5, 'deckCount': 45, 'discard': [], 'prize': [None, None, None, None, None, None], 'handCount': 5, 'hand': None, 'poisoned': False, 'burned': False, 'asleep': False, 'paralyzed': False, 'confused': False}]}, 'search_begin_input': 'BAFEAKQAEEAUBAGEAbEBAGEAEB-kCFQQAIeAOCeAgQwACFQQ-+EQYANBg-ZBIAEMis9PCgMDx8-KBC0-PJFDAOY-ZBBQ-ZBt-1CgADHhk-TBBAETg-JEB-VEQ-VBL-+BI-UBBCw-3LNICACCKAPeA/eAGQC-hSNMCACCI-WBIB-hIGEEACCa-WBIB-3zDAEnQ-VBCABQ-hcDAEhw-VBCABQ-hIDAEgw-VBCABQ-3VwADII-WBgE-3fMADCG-WBIB-3BDAEh-WBCABQ-gSDSABgACiQ-UBEEABg-LjIsEACCZAEiQ-PBQkC*3HBDAEnAEIk-PBEIABg*MBBMADCYAEiQ-PBQgC-MZCQAEgACgAEQAHgACgABBACQAHgACgABCACQAHgACgABDACQAHgACgABEACQAHkACgABFACQAHcABBgAMgACgABHACQAH4-KBQADE8AWQAI=='}


Player 1 observation at step 10:
{'remainingOverageTime': 599.9998670000002, 'select': {'type': 0, 'context': 0, 'minCount': 1, 'maxCount': 1, 'remainDamageCounter': 0, 'remainEnergyCost': 0, 'option': [{'type': 9, 'area': 2, 'index': 0, 'inPlayArea': 4, 'inPlayIndex': 0}, {'type': 7, 'index': 4}, {'type': 13, 'attackId': 1044}, {'type': 13, 'attackId': 1045}, {'type': 14}], 'deck': None, 'contextCard': None, 'effect': None}, 'logs': [{'type': 11, 'playerIndex': 1, 'cardId': 3, 'serial': 100, 'cardIdTarget': 722, 'serialTarget': 67}], 'current': {'turn': 3, 'turnActionCount': 2, 'yourIndex': 1, 'firstPlayer': 1, 'supporterPlayed': False, 'stadiumPlayed': False, 'energyAttached': True, 'retreated': False, 'result': -1, 'stadium': [], 'looking': None, 'players': [{'active': [{'id': 722, 'serial': 6, 'playerIndex': 0, 'hp': 90, 'maxHp': 90, 'appearThisTurn': False, 'energies': [], 'energyCards': [], 'tools': [], 'preEvolution': []}], 'bench': [], 'benchMax': 5, 'deckCount': 46, 'discard': [], 'prize': [None, None, None, None, None, None], 'handCount': 7, 'hand': None, 'poisoned': False, 'burned': False, 'asleep': False, 'paralyzed': False, 'confused': False}, {'active': [{'id': 722, 'serial': 67, 'playerIndex': 1, 'hp': 90, 'maxHp': 90, 'appearThisTurn': False, 'energies': [3, 3], 'energyCards': [{'id': 3, 'serial': 120, 'playerIndex': 1}, {'id': 3, 'serial': 100, 'playerIndex': 1}], 'tools': [{'id': 1163, 'serial': 78, 'playerIndex': 1}], 'preEvolution': []}], 'bench': [], 'benchMax': 5, 'deckCount': 45, 'discard': [], 'prize': [None, None, None, None, None, None], 'handCount': 5, 'hand': [{'id': 723, 'serial': 69, 'playerIndex': 1}, {'id': 3, 'serial': 96, 'playerIndex': 1}, {'id': 3, 'serial': 95, 'playerIndex': 1}, {'id': 3, 'serial': 119, 'playerIndex': 1}, {'id': 722, 'serial': 65, 'playerIndex': 1}], 'poisoned': False, 'burned': False, 'asleep': False, 'paralyzed': False, 'confused': False}]}, 'search_begin_input': 'ABwAEIAPEAUBAGEADQAXEBADBACEAEB-+CCd-lFQYANBg-ZBH-ZBC4-PJFDAOY-ZBBQADEVgX3dB-PBt-1CgADHhk-TBBAETg-JEB-VEQ-VBL-+BI-UBBCw-3LNICACCK-WBQC*MDD0gIACJs-UBBABgE-LFDSABgACiQ-UBEEABg-LFNMCACB7-VBQIB-hcIsEACCZAEiQ-PBQkC-N3wADI-VBBABgE-3BMADB9-VBQIB-3LDAEnAEIk-PBEIABg-39wADJc-UBBABgE-3BMADCYAEiQ-PBQgC-MZBQAEkACgAEQAHcABBAN0ABFABQACP//AG0ABFQQACP//AG4-KBQADE8AWQAI=='}

In [34]:
OPTION_TYPE_ATTACK = 13
OPTION_TYPE_END = 14

def decide_action(obs_dict):
    if obs_dict["select"] is None:
        return deck

    select = obs_dict["select"]
    options = select["option"]

    # Coin toss
    if select["type"] == 9 and select["context"] == 41:
        for i, opt in enumerate(options):
            if opt["type"] == 1:  # YES
                return [i]

    # Main menu - check if any attack option is available
    if select["type"] == 0 and select["context"] == 0:
        attack_options = [(i, opt) for i, opt in enumerate(options) if opt["type"] == OPTION_TYPE_ATTACK]
        if attack_options:
            # For now: just pick the FIRST available attack (we'll add real logic next)
            i, opt = attack_options[0]
            return [i]

    return list(range(select["minCount"]))

In [35]:
print("Starting search...")
found_count = 0

for i, step in enumerate(result):
    for player in [0, 1]:
        obs = step[player]["observation"]
        if obs["select"] is not None and obs["select"]["context"] == 35:
            print(f"Found! Step {i}, Player {player}")
            print(obs["select"])
            found_count += 1

print(f"Search complete. Found {found_count} matches.")

Starting search...
Search complete. Found 0 matches.

In [39]:
OPTION_TYPE_ATTACK = 13

def decide_action(obs_dict):
    if obs_dict["select"] is None:
        return deck

    select = obs_dict["select"]
    options = select["option"]

    if select["type"] == 9 and select["context"] == 41:
        for i, opt in enumerate(options):
            if opt["type"] == 1:
                return [i]

    if select["type"] == 0 and select["context"] == 0:
        attack_options = [(i, opt) for i, opt in enumerate(options) if opt["type"] == OPTION_TYPE_ATTACK]
        if attack_options:
            i, opt = attack_options[0]
            return [i]

    return list(range(select["minCount"]))


# Test directly against the real observation we already captured
test_obs = result[10][1]["observation"]
chosen = decide_action(test_obs)
print("Options available:", test_obs["select"]["option"])
print("Agent chose index:", chosen)
print("That option is:", test_obs["select"]["option"][chosen[0]])

Options available: [{'type': 9, 'area': 2, 'index': 0, 'inPlayArea': 4, 'inPlayIndex': 0}, {'type': 7, 'index': 4}, {'type': 13, 'attackId': 1044}, {'type': 13, 'attackId': 1045}, {'type': 14}]
Agent chose index: [2]
That option is: {'type': 13, 'attackId': 1044}

In [40]:
print(card_lookup[722])

{'name': 'Snover', 'category': 'Basic Pokémon', 'hp': 90.0, 'type': 'Water', 'weakness': 'Metal', 'retreat_cost': 3.0, 'attacks': [{'name': 'Beat', 'cost': ['Water'], 'damage': '10', 'effect': None}, {'name': 'Icy Snow', 'cost': ['Water', 'Water'], 'damage': '30', 'effect': None}]}

In [41]:
# Build a global attack-row counter, matching CSV row order
attack_counter = 0
attack_id_lookup = {}  # maps our_computed_id -> attack details

for _, row in card_data.iterrows():
    if pd.notna(row["Move Name"]):
        attack_counter += 1
        attack_id_lookup[attack_counter] = {
            "card_id": row["Card ID"],
            "card_name": row["Card Name"],
            "move_name": row["Move Name"],
            "cost": parse_energy_cost(row["Cost"]),
            "damage": row["Damage"]
        }

print("Total attacks counted:", attack_counter)
print("\nWhat's at position 1044:", attack_id_lookup.get(1044))
print("What's at position 1045:", attack_id_lookup.get(1045))

Total attacks counted: 1811

What's at position 1044: {'card_id': 606, 'card_name': 'Mienshao', 'move_name': 'Smash Uppercut', 'cost': ['Fighting', 'Fighting'], 'damage': '80'}
What's at position 1045: {'card_id': 607, 'card_name': 'Terrakion', 'move_name': 'Retaliate', 'cost': ['Fighting', 'Colorless'], 'damage': '50'}

In [42]:
collected_data = []

for game_num in range(10):
    result = env.run([random_agent, random_agent])
    for step in result:
        for player in [0, 1]:
            obs = step[player]["observation"]
            for log in obs["logs"]:
                if log["type"] == 15:  # ATTACK log
                    collected_data.append({
                        "card_id": log["cardId"],
                        "attack_id": log["attackId"]
                    })

# Remove duplicates
unique_pairs = list({(d["card_id"], d["attack_id"]) for d in collected_data})
print(f"Collected {len(unique_pairs)} unique (card_id, attack_id) pairs")
for pair in unique_pairs:
    print(pair)

Collected 6 unique (card_id, attack_id) pairs
(722, 1044)
(721, 1042)
(723, 1047)
(723, 1046)
(722, 1045)
(721, 1043)

In [43]:
for cid in [721, 722, 723]:
    print(f"Card {cid}: {card_lookup[cid]['name']}")
    for idx, atk in enumerate(card_lookup[cid]['attacks']):
        print(f"  index {idx}: {atk['name']} - {atk['damage']} dmg - cost {atk['cost']}")
    print()

Card 721: Kyogre
  index 0: Riptide - 20× dmg - cost ['Water']
  index 1: Swirling Waves - 130 dmg - cost ['Water', 'Water', 'Colorless']

Card 722: Snover
  index 0: Beat - 10 dmg - cost ['Water']
  index 1: Icy Snow - 30 dmg - cost ['Water', 'Water']

Card 723: Mega Abomasnow ex
  index 0: Hammer-lanche - 100× dmg - cost ['Water', 'Water']
  index 1: Frost Barrier - 200 dmg - cost ['Water', 'Water', 'Water']

In [44]:
sorted_cards = card_data.sort_values("Card ID")

attack_counter = 1042 - 1  # we'll calibrate starting point based on what we know, but let's first see where Card ID 721 actually starts

# Find where card 721 first appears in sorted order, and what attack count precedes it
position = 0
for _, row in sorted_cards.iterrows():
    if row["Card ID"] == 721:
        print(f"Card 721 first attack would be attackId: {attack_counter + 1}")
        break
    if pd.notna(row["Move Name"]):
        attack_counter += 1

Card 721 first attack would be attackId: 2273

In [45]:
print(card_lookup[721])
print(card_lookup[722])
print(card_lookup[723])

{'name': 'Kyogre', 'category': 'Basic Pokémon', 'hp': 150.0, 'type': 'Water', 'weakness': 'Lightning', 'retreat_cost': 3.0, 'attacks': [{'name': 'Riptide', 'cost': ['Water'], 'damage': '20×', 'effect': 'This attack does 20 damage for each Basic {W} Energy card in your discard pile. Then, shuffle those cards into your deck.'}, {'name': 'Swirling Waves', 'cost': ['Water', 'Water', 'Colorless'], 'damage': '130', 'effect': 'Discard 2 Energy from this Pokémon.'}]}
{'name': 'Snover', 'category': 'Basic Pokémon', 'hp': 90.0, 'type': 'Water', 'weakness': 'Metal', 'retreat_cost': 3.0, 'attacks': [{'name': 'Beat', 'cost': ['Water'], 'damage': '10', 'effect': None}, {'name': 'Icy Snow', 'cost': ['Water', 'Water'], 'damage': '30', 'effect': None}]}
{'name': 'Mega Abomasnow ex', 'category': 'Stage 1 Pokémon', 'hp': 350.0, 'type': 'Water', 'weakness': 'Metal', 'retreat_cost': 4.0, 'attacks': [{'name': 'Hammer-lanche', 'cost': ['Water', 'Water'], 'damage': '100×', 'effect': 'Discard the top 6 cards of your deck, and this attack does 100 damage for each Basic {W} Energy card that you discarded in this way.'}, {'name': 'Frost Barrier', 'cost': ['Water', 'Water', 'Water'], 'damage': '200', 'effect': 'During your opponent’s next turn, this Pokémon takes 30 less damage from attacks (after applying Weakness and Resistance).'}]}

In [47]:
def choose_best_attack(obs_dict, card_lookup):
    select = obs_dict["select"]
    options = select["option"]
    current = obs_dict["current"]
    your_index = current["yourIndex"]
    
    active = current["players"][your_index]["active"][0]
    card_id = active["id"]
    attacks = card_lookup[card_id]["attacks"]
    
    attack_options = [(i, opt) for i, opt in enumerate(options) if opt["type"] == 13]
    
    best_index = None
    best_damage = -1
    
    for i, opt in attack_options:
        position_in_attacks = attack_options.index((i, opt))  # 0, 1, 2... in order seen
        if position_in_attacks < len(attacks):
            attack_info = attacks[position_in_attacks]
            damage_str = str(attack_info["damage"]).replace("×", "").strip()
            damage = int(damage_str) if damage_str.isdigit() else 0
            if damage > best_damage:
                best_damage = damage
                best_index = i
    
    return best_index

In [48]:
test_obs = result[10][1]["observation"]
chosen_index = choose_best_attack(test_obs, card_lookup)

print("Available options:", test_obs["select"]["option"])
print("Chosen index:", chosen_index)
print("Chosen option:", test_obs["select"]["option"][chosen_index])

Available options: [{'type': 8, 'area': 2, 'index': 1, 'inPlayArea': 4, 'inPlayIndex': 0}, {'type': 7, 'index': 2}, {'type': 8, 'area': 2, 'index': 3, 'inPlayArea': 4, 'inPlayIndex': 0}, {'type': 8, 'area': 2, 'index': 5, 'inPlayArea': 4, 'inPlayIndex': 0}, {'type': 14}]
Chosen index: None

TypeError: list indices must be integers or slices, not NoneType

In [49]:
result = env.run([random_agent, random_agent])

# Search this specific game for a real attack-eligible moment
found = False
for i, step in enumerate(result):
    for player in [0, 1]:
        obs = step[player]["observation"]
        if obs["select"] is not None:
            options = obs["select"]["option"]
            if any(opt["type"] == 13 for opt in options):
                print(f"Found attack options at step {i}, player {player}")
                test_obs = obs
                found = True
                break
    if found:
        break

if found:
    chosen_index = choose_best_attack(test_obs, card_lookup)
    print("Available options:", test_obs["select"]["option"])
    print("Chosen index:", chosen_index)
    print("Chosen option:", test_obs["select"]["option"][chosen_index])
else:
    print("No attack options found in this game, try running again")

Found attack options at step 8, player 1
Available options: [{'type': 7, 'index': 0}, {'type': 7, 'index': 5}, {'type': 13, 'attackId': 1042}, {'type': 14}]
Chosen index: 2
Chosen option: {'type': 13, 'attackId': 1042}

In [50]:
result = env.run([random_agent, random_agent])

found = False
for i, step in enumerate(result):
    for player in [0, 1]:
        obs = step[player]["observation"]
        if obs["select"] is not None:
            options = obs["select"]["option"]
            attack_count = sum(1 for opt in options if opt["type"] == 13)
            if attack_count >= 2:
                print(f"Found {attack_count} attack options at step {i}, player {player}")
                test_obs = obs
                found = True
                break
    if found:
        break

if found:
    current = test_obs["current"]
    your_index = current["yourIndex"]
    active = current["players"][your_index]["active"][0]
    card_id = active["id"]
    print("Active Pokemon card ID:", card_id, "-", card_lookup[card_id]["name"])
    print("Its attacks:", card_lookup[card_id]["attacks"])
    
    chosen_index = choose_best_attack(test_obs, card_lookup)
    print("\nAvailable options:", test_obs["select"]["option"])
    print("Chosen index:", chosen_index)
    print("Chosen option:", test_obs["select"]["option"][chosen_index])
else:
    print("No multi-attack moment found, try running again")

Found 2 attack options at step 21, player 1
Active Pokemon card ID: 722 - Snover
Its attacks: [{'name': 'Beat', 'cost': ['Water'], 'damage': '10', 'effect': None}, {'name': 'Icy Snow', 'cost': ['Water', 'Water'], 'damage': '30', 'effect': None}]

Available options: [{'type': 7, 'index': 1}, {'type': 9, 'area': 2, 'index': 3, 'inPlayArea': 4, 'inPlayIndex': 0}, {'type': 7, 'index': 4}, {'type': 9, 'area': 2, 'index': 5, 'inPlayArea': 4, 'inPlayIndex': 0}, {'type': 13, 'attackId': 1044}, {'type': 13, 'attackId': 1045}, {'type': 14}]
Chosen index: 5
Chosen option: {'type': 13, 'attackId': 1045}